name: Hyprland Breaking Change Notifier

on:
  schedule:
  - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        
      - name: Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Update
        run: nix flake update

      - name: Build
        run: nix build --extra-trusted-substituters "https://hyprland.cachix.org" -L
