name: Hyprland Breaking Change Notifier

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: duckonaut/hyprland-arch:latest
    steps:
    - name: Install dependencies
      run: |
        sudo -u user sh -c "paru -Syu --noconfirm aquamarine-git hyprland-git hyprutils-git hyprwayland-scanner-git"
    - name: Checkout current repository
      uses: actions/checkout@v4

    - name: Build current repository
      run: make all
